version: "3.5"

services:
  postgres:
    image: postgres:12.5
    volumes:
      - canada-pgData:/var/lib/postgresql/data
      - ./data/db-dump:/db-dump
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=canada_password
      - POSTGRES_USER=canada_user
      - POSTGRES_DB=canada_db

volumes:
  canada-pgData:
