version: "3.5"

services:
  postgres:
    image: postgres:12.5
    volumes:
      - canada-pgData:/var/lib/postgresql/data
      - ./data/db-dump:/db-dump
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=canada_password
      - POSTGRES_USER=canada_user
      - POSTGRES_DB=canada_db
  front:
    image: node:14.5-buster
    volumes:
      - ./front:/app
    working_dir: "/app"
    command: "yarn start"
    ports:
      - 3000:3000

volumes:
  canada-pgData:
